### ISSUE TITLE
Change Review__c.FundingRequest__c from Lookup to Master-Detail

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/OutboundFundsModule#153]
I'm not sure what the rationale for Lookup was - I can see an argument for separate ownership from the Funding Request, but there is already a separate Assigned To field on the Review object. I can't see a rationale for having Review records **not** assigned to a Funding Request.

But a pretty common feature of grant application reviews is applying numerical scores, and M/D would allow standard Rollup Summary fields from the Review to the Funding Request. I think that this is a new enough addition to the project that making this breaking change would be worthwhile.

**Comment by spelak-salesforce** [comment]
Thank you @tet3 for the suggestion.   We decided **Review** should have a Lookup Relationship to **Funding Request** instead of a Master-Detail Relationship because of sharing.  Any user who has access to a Funding Request _should not_ automatically have access to all related Review records.  Review records can contain sensitive information that requires fine-grain control of who gets to see those records.
