### ISSUE TITLE
Milestone_Record_Page

### ISSUE THREAD

**Issue by sharicarlson13** [SalesforceFoundation/OutboundFundsModule#34]
The Requirements Lightning Record Page in the package is called MIlestone_Record_Page. This is a hold over from the previous name of the object and should probably be renamed, if possible in a future release.

**Comment by Nickers3** [comment]
Compact Layout and other metadata is also listed as Milestone.  Should complete a whole audit of the Requirement Object and update.

**Comment by Nickers3** [comment]
@sharireily, potential Atlanta Sprint Item

**Comment by sharireily** [comment]
Conversation Notes - 

Package 1 deploys new and rename old to deprecated - don't use
Package 3 remove deprecated 

Package 1 deploys new and removes old 
Then they can remove if needed 

Just change label ? 
Test what happens, but should happen
- Shari will ask at North Peak for alternate methods
- 
Push correct record page right so that people use the right one

Where can "milestone" be found - 
Record Page 
Page Layout 
Compact layout
Report (Requests with Upcoming Milestones)

**Comment by kschaefges** [comment]
Salesforce has determined that this issue will not be explored further.
